import Link from "next/link";

export const dynamic = "force-static";

export default function EulaPage() {
  return (
    <main className="legal-page">
      <Link className="brand" href="/">
        seed<span>.</span>
      </Link>
      <article>
        <p className="eyebrow">Legal</p>
        <h1>End User License Agreement (EULA)</h1>
        <p>
          This End User License Agreement (&quot;Agreement&quot;) is a legal agreement between you (&quot;User&quot; or &quot;you&quot;) and Seed Web Builder (&quot;Seed&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) governing your access to and use of the Seed AI website builder, technical manager, and integration services.
        </p>

        <h2>1. Grant of License</h2>
        <p>
          Seed grants you a non-exclusive, non-transferable, revocable license to use the Seed management dashboard and integration tools to orchestrate and deploy web applications to your own infrastructure accounts.
        </p>

        <h2>2. Ownership of Code and Generated Assets</h2>
        <p>
          <strong>You own everything you create.</strong> All source code, database schemas, styling, copy, domain names, and application assets generated by Seed on your behalf are your exclusive property. Seed claims no proprietary ownership over applications deployed to your GitHub, Supabase, or Vercel accounts.
        </p>

        <h2>3. Third-Party Services &amp; Accounts</h2>
        <p>
          Seed acts as an authorized agent for your third-party provider accounts (GitHub, Supabase, Vercel, and OpenAI). You acknowledge and agree that:
        </p>
        <ul>
          <li>You are responsible for complying with the Terms of Service of each third-party provider.</li>
          <li>You are responsible for any charges or subscription fees incurred under your third-party provider accounts.</li>
          <li>Seed requests only the minimum necessary permissions to perform requested deployment and management tasks.</li>
        </ul>

        <h2>4. User Responsibilities &amp; Acceptable Use</h2>
        <p>
          You agree not to use Seed to generate, build, or deploy:
        </p>
        <ul>
          <li>Malware, phishing pages, or software designed to compromise security or privacy.</li>
          <li>Content that infringes intellectual property rights, copyrights, or trademarks.</li>
          <li>Applications promoting illegal activities, fraud, or hate speech.</li>
        </ul>

        <h2>5. Disclaimer of Warranties</h2>
        <p>
          Seed is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without warranties of any kind. While Seed incorporates safety guardrails and automated checks, you are responsible for reviewing and testing your generated applications prior to production use.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          In no event shall Seed be liable for any indirect, incidental, special, consequential, or punitive damages arising from the use or inability to use Seed, including data loss or service interruption of third-party platforms.
        </p>

        <h2>7. Termination &amp; Revocation</h2>
        <p>
          You may terminate this Agreement at any time by disconnecting your integrations and discontinuing use of Seed. Termination will not affect your independent ownership of code, databases, and websites deployed in your own provider accounts.
        </p>
      </article>
    </main>
  );
}
