"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Building2, CalendarDays, Check, ContactRound, Sparkles } from "lucide-react";

const projectTypes = [{id:"business",title:"Business website",copy:"Tell customers who you are and what you do.",icon:Building2},{id:"lead",title:"Lead website",copy:"Collect enquiries from interested customers.",icon:ContactRound},{id:"booking",title:"Booking website",copy:"Let customers view services and request a time.",icon:CalendarDays}];
export function OnboardingFlow({name}:{name:string}) { const router=useRouter(); const [step,setStep]=useState(0); const [type,setType]=useState("booking"); const [business,setBusiness]=useState("Shikha Yoga"); const [features,setFeatures]=useState(["Learn about classes","Contact me","Book a class"]); const [creating,setCreating]=useState(false); const toggle=(value:string)=>setFeatures(items=>items.includes(value)?items.filter(item=>item!==value):[...items,value]); const createProject=async()=>{setCreating(true);const response=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:business,projectType:`${type}_website`,features})});setCreating(false);if(response.ok)router.push("/dashboard")};
  return <main className="onboarding-page"><header><Link className="brand" href="/">seed<span>.</span></Link><div className="onboarding-progress"><span>{step+1} of 3</span><div><i style={{width:`${((step+1)/3)*100}%`}}/></div></div></header><section className="onboarding-card">{step===0&&<><div className="seed-mark"><Sparkles size={20}/></div><p className="eyebrow">Hi {name}</p><h1>What do you want<br/>to build?</h1><p className="intro">Start with one reliable website. You can ask Seed to change it later.</p><div className="type-grid">{projectTypes.map(item=><button className={`type-option ${type===item.id?"selected":""}`} onClick={()=>setType(item.id)} key={item.id}><item.icon/><span><b>{item.title}</b><small>{item.copy}</small></span>{type===item.id&&<Check className="option-check" size={18}/>}</button>)}</div></>}{step===1&&<><p className="eyebrow">About your business</p><h1>What is your business called?</h1><p className="intro">Seed will use this as the project name. You can change it anytime.</p><label className="field-label">Business name<input autoFocus value={business} onChange={event=>setBusiness(event.target.value)} placeholder="e.g. Shikha Yoga"/></label></>}{step===2&&<><p className="eyebrow">One last thing</p><h1>What should customers be able to do?</h1><p className="intro">Choose the essentials. Seed keeps the first version focused and reliable.</p><div className="choice-list">{["Learn about classes","Contact me","Book a class"].map(item=><button className={features.includes(item)?"chosen":""} onClick={()=>toggle(item)} key={item}><span>{features.includes(item)?<Check size={18}/>:<i/>}</span>{item}</button>)}</div><div className="ready-note"><Sparkles size={18}/><p><b>Your plan is ready</b><small>{business || "Your business"} · {projectTypes.find(item=>item.id===type)?.title} · {features.length} features</small></p></div></>}</section><footer className="onboarding-footer"><button className="back-button" onClick={()=>setStep(value=>Math.max(0,value-1))} disabled={step===0}>Back</button>{step<2?<button className="button button-dark" onClick={()=>setStep(value=>value+1)} disabled={step===1&&!business.trim()}>Continue <ArrowRight size={16}/></button>:<button className="button button-dark" onClick={createProject} disabled={creating}>{creating?"Creating…":"Create my project"} <ArrowRight size={16}/></button>}</footer></main>;
}
