import "server-only";
import type { RepositoryState, SourceProvider } from "@/lib/providers/contracts";

type GitHubFile = { path: string; content: string };
export class GitHubSourceProvider implements SourceProvider {
  constructor(private token: string, private owner: string, private repo: string, private branch = "main") {}
  private async request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`https://api.github.com${path}`, { ...init, headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${this.token}`, "X-GitHub-Api-Version": "2022-11-28", ...init?.headers } }); if (!response.ok) throw new Error(`GitHub operation failed (${response.status}).`); return response.json() as Promise<T>; }
  async getRepositoryState(): Promise<RepositoryState> { const ref = await this.request<{ object: { sha: string } }>(`/repos/${this.owner}/${this.repo}/git/ref/heads/${this.branch}`); const tree = await this.request<{ tree: Array<{ path: string; sha: string; type: string }> }>(`/repos/${this.owner}/${this.repo}/git/trees/${ref.object.sha}?recursive=1`); return { commitSha: ref.object.sha, files: tree.tree.filter(item => item.type === "blob").map(item => ({ path: item.path, sha: item.sha })) }; }
  async createRepository(name: string) { const repository = await this.request<{ id: number; html_url: string }>("/user/repos", { method: "POST", body: JSON.stringify({ name, private: true, auto_init: true }) }); return { id: String(repository.id), url: repository.html_url }; }
  async readFiles(paths?: string[]): Promise<GitHubFile[]> { const state = await this.getRepositoryState(); const selected = paths ?? state.files.map(file => file.path); return Promise.all(selected.map(async path => { const file = await this.request<{ content: string; encoding: string }>(`/repos/${this.owner}/${this.repo}/contents/${encodeURIComponent(path)}?ref=${this.branch}`); return { path, content: file.encoding === "base64" ? Buffer.from(file.content.replace(/\n/g, ""), "base64").toString("utf8") : file.content }; })); }
  async createBranch(name: string) { const state = await this.getRepositoryState(); await this.request(`/repos/${this.owner}/${this.repo}/git/refs`, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${name}`, sha: state.commitSha }) }); this.branch = name; }
  async writeFiles(files: GitHubFile[]) { for (const file of files) { const current = await this.request<{ sha: string }>(`/repos/${this.owner}/${this.repo}/contents/${encodeURIComponent(file.path)}?ref=${this.branch}`).catch(() => null); await this.request(`/repos/${this.owner}/${this.repo}/contents/${encodeURIComponent(file.path)}`, { method: "PUT", body: JSON.stringify({ message: `Seed: update ${file.path}`, content: Buffer.from(file.content).toString("base64"), branch: this.branch, ...(current ? { sha: current.sha } : {}) }) }); } }
  async commitChanges() { const state = await this.getRepositoryState(); return { sha: state.commitSha }; }
}
